sudo: true
language: java
jdk:
- oraclejdk8
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-dev libboost-test-dev libboost-program-options-dev libboost-system-dev libboost-filesystem-dev libevent-dev automake libtool flex bison pkg-config g++ libssl-dev ant
  - wget http://ftp.debian.org/debian/pool/main/a/automake-1.14/automake_1.14.1-3_all.deb
  - sudo dpkg -i automake_1.14.1-3_all.deb
  - wget http://www.us.apache.org/dist/thrift/0.9.3/thrift-0.9.3.tar.gz
  - tar xfz thrift-0.9.3.tar.gz
  - cd thrift-0.9.3 && ./configure && sudo make install
